!*******************************************************************************
! Copyright (c) 2025, Salvador R.G. Balestra
!
! This file is part of the SOD package.
!
! SOD is free software: you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation, either version 3 of the License, or
! (at your option) any later version.
!
!******************************************************************************

!*******************************************************************************
! used to evaluate S_conf = k_B ln W for each substitution level.
! Computes configurational entropies from OUTSOD_Nxxxx files generated by the
! Calcula entropías configuracionales a partir de archivos OUTSOD_Nxxxx generados por el
! exhaustive enumerator. Energies are not required; only degeneracy counts are
! enumerador exhaustivo. No se requieren energías; solo se usan recuentos de degeneración
! para evaluar S_conf = k_B ln W para cada nivel de sustitución.
!*******************************************************************************
module entropy
    use consts
    use cli, only: build_level_sequence, compose_mode_command, is_help_token, parse_level_spec
    use utils, only: format_level_directory, join_path
    use, intrinsic :: iso_fortran_env, only: output_unit, error_unit
    implicit none

    integer, parameter :: max_scan_level = 9999
    real(dp), parameter :: ev_to_joule = 1.602176634d-19
    real(dp), parameter :: avogadro = 6.02214076d23

contains

    subroutine run_sod_ensemble_entropy(arg_offset)
        integer, intent(in), optional :: arg_offset
        integer :: level_min, level_max
        integer, allocatable :: requested_levels(:)
        integer, allocatable :: levels(:)
        logical :: has_list
        logical :: found_reference
        integer :: ref_total_sites
        integer :: idx
        integer :: summary_unit
        character(len=*), parameter :: summary_name = 'sod_entropy_summary.csv'
        logical :: any_level

        call parse_arguments(level_min, level_max, requested_levels, has_list, arg_offset)

        ref_total_sites = -1
        found_reference = detect_reference_sites(ref_total_sites)
        if (.not. found_reference) then
            write(error_unit,'(A)') 'Error: no OUTSOD files were found in the current directory or xNN folders.'
            stop 1
        end if

        call build_level_sequence(level_min, level_max, requested_levels, has_list, ref_total_sites, levels)
        if (.not. allocated(levels) .or. size(levels) == 0) then
            write(error_unit,'(A)') 'Error: the -N specification did not produce any valid levels.'
            stop 1
        end if

        call init_summary(summary_unit, summary_name)

        write(*,'(A)') '--- Configurational entropy from OUTSOD ---'
        write(*,'(A,I0)') 'Substitutable sites (npos): ', ref_total_sites
        if (has_list) then
            write(*,'(A)', advance='no') 'Requested levels: '
            do idx = 1, size(levels)
                if (idx > 1) write(*,'(A)', advance='no') ', '
                write(*,'(I0)', advance='no') levels(idx)
            end do
            write(*,*)
        else
            write(*,'(A,I0,A,I0)') 'Levels evaluated: ', levels(1), ' .. ', levels(size(levels))
        end if
        write(*,*)
        flush(output_unit)

        any_level = .false.
        do idx = 1, size(levels)
            call process_level(levels(idx), ref_total_sites, summary_unit, any_level)
        end do

        close(summary_unit)

        if (.not. any_level) then
            write(error_unit,'(A)') 'Warning: no levels could be processed. Check the OUTSOD files.'
            stop 1
        end if
    end subroutine run_sod_ensemble_entropy

    subroutine parse_arguments(level_min, level_max, level_list, has_list, arg_offset)
        integer, intent(out) :: level_min, level_max
        integer, allocatable, intent(out) :: level_list(:)
        logical, intent(out) :: has_list
        integer, intent(in), optional :: arg_offset
        integer :: argc, iarg, offset
        character(len=256) :: arg, spec

        level_min = 0
        level_max = -1
        has_list = .false.
        allocate(level_list(0))

        argc = command_argument_count()
        offset = 0
        if (present(arg_offset)) offset = max(0, arg_offset)
        if (argc <= offset) return

        iarg = 1 + offset
        do while (iarg <= argc)
            call get_command_argument(iarg, arg)
            if (is_help_token(arg)) then
                call print_usage()
                stop
            end if

            select case (trim(adjustl(arg)))
            case ('-N','-n')
                if (iarg + 1 > argc) then
                    write(error_unit,'(A)') 'Error: missing specification after -N.'
                    call print_usage()
                    stop 1
                end if
                call get_command_argument(iarg + 1, spec)
                call parse_level_spec(spec, level_min, level_max, level_list, has_list)
                iarg = iarg + 2
            case default
                write(error_unit,'(A)') 'Error: unrecognized argument. Use --help for more information.'
                call print_usage()
                stop 1
            end select
        end do
    end subroutine parse_arguments

    subroutine print_usage()
        character(len=256) :: command_name

        command_name = compose_mode_command('entropy')
        write(*,'(A)') 'Usage: '//trim(command_name)//' [-N <specification>]'
        write(*,'(A)') ''
        write(*,'(A)') 'Aliases: entropy, sconf'
        write(*,'(A)') ''
        write(*,'(A)') '  -N spec   Defines the levels to evaluate:'
        write(*,'(A)') '            -N -1       -> all available levels'
        write(*,'(A)') '            -N 12       -> only level 12'
        write(*,'(A)') '            -N 3:8      -> levels 3 through 8'
        write(*,'(A)') '            -N 5,9,11   -> explicit list (order preserved)'
        write(*,'(A)') ''
        write(*,'(A)') 'The program reads exact OUTSOD files from either the current directory'
        write(*,'(A)') '(legacy OUTSOD_Nxxxx layout) or xNN/OUTSOD folders and computes'
        write(*,'(A)') 'the configurational entropy S = k_B ln W from the listed degeneracies.'
        write(*,'(A)') 'The aggregated output is written to sod_entropy_summary.csv.'
    end subroutine print_usage

    logical function detect_reference_sites(total_sites)
        integer, intent(out) :: total_sites
        integer :: level
        integer :: dummy_unique

        total_sites = -1
        detect_reference_sites = .false.
        do level = 0, max_scan_level
            if (read_outsod_header(level, total_sites, dummy_unique)) then
                detect_reference_sites = .true.
                return
            end if
        end do
    end function detect_reference_sites

    logical function read_outsod_header(level, total_sites, unique_configs)
        integer, intent(in) :: level
        integer, intent(out) :: total_sites, unique_configs
        character(len=512) :: outsod_name
        integer :: unit, ios
        character(len=256) :: line
        character(len=32) :: word
        integer :: dummy_level

        call locate_outsod_file(level, outsod_name, read_outsod_header)
        if (.not. read_outsod_header) then
            total_sites = -1
            unique_configs = 0
            return
        end if

        open(newunit=unit, file=trim(outsod_name), status='old', action='read', iostat=ios)
        if (ios /= 0) then
            read_outsod_header = .false.
            total_sites = -1
            unique_configs = 0
            return
        end if

        read(unit,'(A)', iostat=ios) line
        if (ios /= 0) then
            close(unit)
            read_outsod_header = .false.
            total_sites = -1
            unique_configs = 0
            return
        end if

        read(line,*, iostat=ios) dummy_level, word, word, total_sites
        if (ios /= 0) then
            close(unit)
            read_outsod_header = .false.
            total_sites = -1
            unique_configs = 0
            return
        end if

        read(unit,'(A)', iostat=ios) line
        if (ios /= 0) then
            close(unit)
            read_outsod_header = .false.
            total_sites = -1
            unique_configs = 0
            return
        end if

        read(line,*, iostat=ios) unique_configs
        if (ios /= 0) unique_configs = 0

        close(unit)
        read_outsod_header = .true.
    end function read_outsod_header

    subroutine init_summary(unit, filename)
        integer, intent(out) :: unit
        character(len=*), intent(in) :: filename
        integer :: ios

        open(newunit=unit, file=trim(filename), status='replace', action='write', iostat=ios)
        if (ios /= 0) then
            write(error_unit,'(A)') 'Error: failed to create the summary file.'
            stop 1
        end if
        write(unit,'(A)') '#N,FracY,UniqueConfigs,TotalWeight,Log10TotalWeight,S_conf_eV_per_K,S_conf_per_site_eV_per_K,'// &
            'S_conf_J_per_K_mol,S_max_eV_per_K,S_ideal_eV_per_K,EntropyReduction_eV_per_K'
    end subroutine init_summary

    subroutine process_level(level, ref_total_sites, summary_unit, any_level)
        integer, intent(in) :: level, ref_total_sites, summary_unit
        logical, intent(inout) :: any_level
        logical :: success
        integer :: total_sites, unique_configs
        real(dp) :: total_weight, log_total_weight
        real(dp) :: frac_ge
        real(dp) :: s_conf, s_conf_per_site, s_conf_per_mol
        real(dp) :: s_max, s_ideal, reduction
        real(dp) :: log_total_comb

        call compute_entropy(level, ref_total_sites, total_sites, unique_configs, total_weight, log_total_weight, &
            log_total_comb, s_conf, s_max, s_ideal, success)

        if (.not. success) return

        any_level = .true.

        if (total_weight <= 0.0_dp) then
            s_conf = 0.0_dp
            log_total_weight = -huge(1.0_dp)
        end if

        frac_ge = 0.0_dp
        if (total_sites > 0) frac_ge = real(level, dp) / real(total_sites, dp)

        if (total_sites > 0) then
            s_conf_per_site = s_conf / real(total_sites, dp)
        else
            s_conf_per_site = 0.0_dp
        end if

        s_conf_per_mol = s_conf * ev_to_joule * avogadro
        reduction = s_max - s_conf

        write(*,'(A)') repeat('-', 72)
        write(*,'(A,I0)') 'Level: ', level
        write(*,'(A,I0)') 'Total sites (npos): ', total_sites
        write(*,'(A,I0)') 'Unique configurations: ', unique_configs
        write(*,'(A,1PE15.6)') 'Total weight (sum of degeneracies): ', total_weight
        if (log_total_weight > -huge(1.0_dp)/2.0_dp) then
            write(*,'(A,F12.6)') 'k_B ln W [eV/K]: ', s_conf
        else
            write(*,'(A)') 'k_B ln W [eV/K]: --'
        end if
        write(*,'(A,F12.6)') 'Maximum entropy (no symmetry reduction) [eV/K]: ', s_max
        write(*,'(A,F12.6)') 'Ideal binary-mixing entropy [eV/K]: ', s_ideal
        write(*,'(A,F12.6)') 'Entropy per site [eV/K]: ', s_conf_per_site
        write(*,'(A,F12.6)') 'Molar entropy [J/K/mol]: ', s_conf_per_mol
        write(*,'(A,F12.6)') 'Entropy reduction (S_max - S_conf) [eV/K]: ', reduction
        flush(output_unit)

        write(summary_unit,'(I0,",",F7.4,",",I0,",",ES16.8,",",F12.6,",",F12.6,",",F12.6,",",F12.6,",",F12.6,",",F12.6,",",F12.6)') &
            level, frac_ge, unique_configs, total_weight, log10_from_log(log_total_weight), s_conf, s_conf_per_site, &
            s_conf_per_mol, s_max, s_ideal, reduction
    end subroutine process_level

    subroutine compute_entropy(level, ref_total_sites, total_sites, unique_configs, total_weight, log_total_weight, &
                               log_total_comb, s_conf, s_max, s_ideal, success)
        integer, intent(in) :: level, ref_total_sites
        integer, intent(out) :: total_sites, unique_configs
        real(dp), intent(out) :: total_weight, log_total_weight, log_total_comb
        real(dp), intent(out) :: s_conf, s_max, s_ideal
        logical, intent(out) :: success
        character(len=512) :: outsod_name
        integer :: unit, ios
        character(len=256) :: line
        integer :: idx, deg
        real(dp) :: sum_deg
        integer :: header_level, header_sites
        character(len=32) :: word
        real(dp) :: frac

        call locate_outsod_file(level, outsod_name, success)
        if (.not. success) return

        open(newunit=unit, file=trim(outsod_name), status='old', action='read', iostat=ios)
        if (ios /= 0) then
            success = .false.
            return
        end if

        read(unit,'(A)', iostat=ios) line
        if (ios /= 0) then
            close(unit)
            success = .false.
            return
        end if
        read(line,*, iostat=ios) header_level, word, word, header_sites
        if (ios /= 0) then
            close(unit)
            success = .false.
            return
        end if

        read(unit,'(A)', iostat=ios) line
        if (ios /= 0) then
            close(unit)
            success = .false.
            return
        end if

        sum_deg = 0.0_dp
        unique_configs = 0
        do
            read(unit,*, iostat=ios) idx, deg
            if (ios /= 0) exit
            sum_deg = sum_deg + real(deg, dp)
            unique_configs = unique_configs + 1
        end do
        close(unit)

        total_sites = header_sites
        if (ref_total_sites >= 0 .and. total_sites /= ref_total_sites) then
            write(error_unit,'(A,I0,A,I0)') 'Warning: OUTSOD_N', level, ' reports npos=', total_sites, &
                ' which differs from the reference value.'
        end if

        total_weight = sum_deg
        if (total_weight > 0.0_dp) then
            log_total_weight = log(total_weight)
            s_conf = kB_eVk * log_total_weight
        else
            log_total_weight = -huge(1.0_dp)
            s_conf = 0.0_dp
        end if

        log_total_comb = log_binomial_real(total_sites, level)
        s_max = kB_eVk * log_total_comb

        if (total_sites > 0) then
            frac = real(level, dp) / real(total_sites, dp)
            if (frac <= 0.0_dp .or. frac >= 1.0_dp) then
                s_ideal = 0.0_dp
            else
                s_ideal = -real(total_sites, dp) * kB_eVk * (frac * log(frac) + (1.0_dp - frac) * log(1.0_dp - frac))
            end if
        else
            s_ideal = 0.0_dp
        end if

        success = .true.
    end subroutine compute_entropy

    subroutine locate_outsod_file(level, path, found)
        integer, intent(in) :: level
        character(len=*), intent(out) :: path
        logical, intent(out) :: found
        character(len=64) :: legacy_name
        character(len=32) :: level_dir

        write(legacy_name,'("OUTSOD_N",I4.4)') level
        inquire(file=trim(legacy_name), exist=found)
        if (found) then
            path = trim(legacy_name)
            return
        end if

        level_dir = format_level_directory('x', level)
        path = join_path(trim(level_dir), 'OUTSOD')
        inquire(file=trim(path), exist=found)
    end subroutine locate_outsod_file

    real(dp) function log_binomial_real(n, k)
        integer, intent(in) :: n, k
        real(dp) :: nn, kk

        if (k < 0 .or. k > n) then
            log_binomial_real = -huge(1.0_dp)
            return
        end if
        if (k == 0 .or. k == n) then
            log_binomial_real = 0.0_dp
            return
        end if

        nn = real(n + 1, dp)
        kk = real(k + 1, dp)
        log_binomial_real = log_gamma(nn) - log_gamma(kk) - log_gamma(real(n - k + 1, dp))
    end function log_binomial_real

    real(dp) function log10_from_log(log_x)
        real(dp), intent(in) :: log_x
        real(dp), parameter :: ln10 = log(10.0_dp)

        if (log_x <= -huge(1.0_dp)/4.0_dp) then
            log10_from_log = -999.0_dp
        else
            log10_from_log = log_x / ln10
        end if
    end function log10_from_log
end module entropy
